name: flutter_keychain_plus
description: "Flutter secure storage via Keychain and Keystore"
version: 0.0.3
repository: https://github.com/Yadav-Sunil/flutter_keychain_plus

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.appmire.flutter_keychain_plus
        pluginClass: FlutterKeychainPlusPlugin
      ios:
        pluginClass: FlutterKeychainPlusPlugin